// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jexhqfksnhzvgqkjadzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpleGhxZmtzbmh6dmdxa2phZHpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NTQwMTksImV4cCI6MjA2MzMzMDAxOX0.gMw5j-1K7dO5omObdQK04vqKxHefXhP0cbFifPeh8pc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);